#!/bin/sh -e

git fetch "https://gitlab.freedesktop.org/mawww/libxft.git" "bgra-glyphs"
git checkout -b "mawww/libxft-bgra-glyphs" FETCH_HEAD

./autogen.sh
./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install
