#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-guile \
    --without-p11-kit

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
