#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-xwayland \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-xorg \
    --enable-suid-wrapper \
    --with-sha1=libcrypto

make DESTDIR="$1" install
