#!/bin/sh -e

ln -s waf-2.0.18 waf

python waf configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --confdir=/etc/mpv \
    --enable-alsa \
    --enable-libass

python waf build
python waf install --destdir="$1"

mkdir -pv "$1/usr/share/mpv/scripts"
cp -av TOOLS/lua/* \
    "$1/usr/share/mpv/scripts/"
