#!/bin/sh -e

#gcc 10 fix
patch -Np1 -i systemd-245-gcc_10-fixes-1.patch

#Create a symlink to work around missing xsltproc
ln -sf /tools/bin/true /usr/bin/xsltproc

#Set up the man pages
tar -xf systemd-man-pages-245.tar.xz

#Remove tests that cannot be built in chroot
sed '179,$ d' -i src/resolve/meson.build

#Remove an unneeded group, render, from the default udev rules
sed -i 's/GROUP="render", //' rules.d/50-udev-default.rules.in

mkdir -p build
cd       build

LANG=en_US.UTF-8                   \
meson --prefix=/usr                \
      --sysconfdir=/etc            \
      --localstatedir=/var         \
     -Dc_args=-Wno-format-overflow \
      -Dblkid=true                 \
      -Dbuildtype=release          \
      -Ddefault-dnssec=no          \
      -Dfirstboot=false            \
      -Dinstall-tests=false        \
      -Dkmod-path=/bin/kmod        \
      -Dldconfig=false             \
      -Dmount-path=/bin/mount      \
      -Drootprefix=                \
      -Drootlibdir=/lib            \
      -Dsplit-usr=true             \
      -Dsulogin-path=/sbin/sulogin \
      -Dsysusers=false             \
      -Dumount-path=/bin/umount    \
      -Db_lto=false                \
      -Drpmmacrosdir=no            \
      -Dhomed=false                \
      -Duserdb=false               \
      -Dman=true                   \
      ..

LANG=en_US.UTF-8 ninja

LANG=en_US.UTF-8 DESTDIR="$1" ninja install

rm -fv "$1/usr/lib/lib{blkid,uuid,mount}.so*"

rm -fv /usr/bin/xsltproc
