#!/bin/sh -e

./configure --prefix=/usr             \
    --enable-unicode-properties       \
    --enable-pcre16                   \
    --enable-pcre32                   \
    --enable-pcregrep-libz            \
    --enable-pcregrep-libbz2          \
    --enable-pcretest-libreadline     \
    --disable-static 

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
